### ISSUE TITLE
[BUG] error(zwlr_layer_surface_v1@41, 2, "layer_surface has never been configured")

### ISSUE THREAD

**Issue by madonuko** [pentamassiv/gtk4-layer-shell-gir#28]
Running `gtk4-layer-shell` 0.2.0 on my computer under Wayfire causes this (consistently):
- [logs](https://gist.github.com/madonuko/542ccc9ffc05eb0a3e6adfcb7bc0760d)
- [code](https://github.com/tau-OS/kumo/blob/main/shizuku/src/widget.rs#L84)

This issue is not reproducible on my colleagues' computers and only my machine with Wayfire. Not reproducible under Sway.

Changing the code to this also causes the issue:
```rs
let window = libhelium::Window::new();
window.init_layer_shell();
window.set_layer(Layer::Overlay);
```

The problem seems to be that its buffers get attached before configure(). I've talked to the Wayfire devs (big thanks to everyone there!) and we've confirmed the issue comes from `gtk4-layer-shell`.

**Comment by pentamassiv** [comment]
I'd be surprised if it has to do with the Rust bindings, since they are just an autogenerated wrapper of the C library, but we can leave this issue open so others can see it

**Comment by Ferdi265** [comment]
I am able to reproduce this issue with the `gtk4-layer-shell` example "simple-example" with the following patch:

```patch
diff --git a/gtk4-layer-shell/examples/simple-example.rs b/gtk4-layer-shell/examples/simple-example.rs
index 32fa01d..8afa307 100644
--- a/gtk4-layer-shell/examples/simple-example.rs
+++ b/gtk4-layer-shell/examples/simple-example.rs
@@ -22,6 +22,10 @@ fn activate(application: &gtk::Application) {
     window.set_margin(Edge::Right, 40);
     window.set_margin(Edge::Top, 20);
 
+    window.connect_map(move |window| {
+        window.set_margin(Edge::Top, 30);
+    });
+
     // ... or like this
     // Anchors are if the window is pinned to each edge of the output
     let anchors = [
```

**Comment by Ferdi265** [comment]
This appears to be an upstream issue, as the [same reproducer](https://github.com/wmww/gtk4-layer-shell/issues/34#issuecomment-2356912673) works in the other bindings and in C as well.

**Comment by madonuko** [comment]
Seems to be fixed by https://github.com/wmww/gtk4-layer-shell/pull/49 (thank you!)
