### ISSUE TITLE
Update gtk4 depency

### ISSUE THREAD

**Issue by BigfootN** [pentamassiv/gtk4-layer-shell-gir#30]
Hello,

Today the `gtk4` dependency version is `0.7`. Today the latest version of `gtk4` is `0.8.1`.

Unfortunately if one wishes to use `gtk4-layer-shell` with `gtk4` he needs to be in `0.7` (according to the version of this package), otherwise there is a conflict.

Another problem would be if one wishes to use `relm4` (latest version, `0.8.1`) with this crate. It is impossible due to conflicting `gtk4` versions.

Could you please update the `gtk4` version used ?

Thank you very much in advance

**Comment by pentamassiv** [comment]
Done :-)

**Comment by BigfootN** [comment]
Thank you
